### ISSUE TITLE
ошибка в работе программы

### ISSUE THREAD

**Issue by kyper999** [MonkAlex/MangaReader#110]
1) В двух последних обновлениях не запускалась автопроверка обновлений (манги), запуск происходил, в логах появлялся длинный текст ошибки и стоял на месте. Мне приходилось закрывать программу и вручную запускать проверку. Это было еще в предыдущей версии.
В последней автопроверка вроде запускается, но ничего не проверяет (новые главы не появляются), хотя если запустить вручную, то находит обновления. Так же ошибка, в логах, с длинным текстом появляется только при первом запуске.
2) В последней версии появилась ошибка в скачивании некоторых глав, т.е. папка с главой появилась, но она оказалась пустой.
Лог 76мб за 1 день
[https://yadi.sk/i/X8CslMqh3Rm7og](url)
UPD: залил лог на гитхаб на всякий случай [MangaReader.20180124.zip](https://github.com/MonkAlex/MangaReader/files/1664851/MangaReader.20180124.zip)

**Comment by MonkAlex** [comment]
@kyper999 в логе обе указанные ошибки? Вечером лог гляну.

**Comment by kyper999** [comment]
в логах за весь день (запуск программы, в ручную запуск проверки обновления и все за весь день, файл за следующий день пока пустой)
да, должны быть обе ошибки. В логах вывело что проверка закончена

**Comment by kyper999** [comment]
Так же заметил, что начал использовать много ресурсов: ЦП 50% и оперативка 600мб. Скорее всего связано с этими ошибками

**Comment by MonkAlex** [comment]
@kyper999 по ресурсам ничего не скажу, просто в фоне висящий процесс 50% CPU жрать не должен. Посмотришь уже после исправления видимо.

**Comment by MonkAlex** [comment]
1. Так, проблему с автоскачиванием я уже починил, но релиза пока не было. Попадёт в ближайший.
2. Папка может быть пустой, если ни один файл в итоге не удалось скачать. Учитывая, что ридманга судя по логу часто отвечает что файл не найден - вполне может быть такое. 
3. Судя по логу - ридманга какую то защиту от скачивания прикрутила, пока не уверен, что с неё ваще будет что-то качаться. Разберусь.

**Comment by MonkAlex** [comment]
Окей, у ридманги больше похоже на косяк, чем на защиту, будет качаться.
Когда релиз - точно не скажу, постараюсь на этой неделе.

**Comment by kyper999** [comment]
такая же ошибка при автообновлении.
лог почистил от лишнего
[MangaReader.20180201.log](https://github.com/MonkAlex/MangaReader/files/1688430/MangaReader.20180201.log)

**Comment by MonkAlex** [comment]
@kyper999 ага, другая ошибка. В настройках программы смени сортировку. У тебя щас сделана по имени, любая другая будет работать.

Промахнулся с именем, починю когда нибудь.

**Comment by MonkAlex** [comment]
В теории исправлено (написал тестов, надеюсь больше не пролезет), но выкладывать наверно буду только со следующим билдом, а в него пока больше нечего включать.
