### ISSUE TITLE
Ошибка в логах

### ISSUE THREAD

**Issue by ftugit** [MonkAlex/MangaReader#112]
Во время обновления у меня были ошибки в логах.
Прошу проверить, вдруг важное и опасное.

[MangaReader.20180226.log](https://github.com/MonkAlex/MangaReader/files/1761240/MangaReader.20180226.log)

**Comment by MonkAlex** [comment]
Ошибки в основном со стороны акомикса вроде.
Если с него хоть что-то скачалось - значит просто сайт перегружен и не отдает нормально с первой попытки страницы.
