### ISSUE TITLE
Работа с двумя мониторами.

### ISSUE THREAD

**Issue by TristisOris** [MonkAlex/MangaReader#115]
программа запускается на фантомных мониторах.

суть:
обычно запуск производится на втором мониторе, позиция запоминается, здесь все правильно.
когда монитор отключен и исчезает из системы, программа продолжает запускаться на нем. иконка на панели появляется, но окно не существует и win+arrow не работает.
частый косяк многих приложений.

**Comment by MonkAlex** [comment]
Не обещаю что быстро, есть и другие баги в работе.

В целом, выглядит несложно, постараюсь в пару недель починить.

А вот когда я всё таки выложу свежий релиз - пока не уверен, хочется добить до рабочего состояния кроссплатформенную альфа-версию. Она тупо ждёт пары мелочей.

**Comment by TristisOris** [comment]
проблема распространенная но не особо критичная. страдают разве что владельцы ноутбуков, после работы за монитором.
