### ISSUE TITLE
странное поведение обновления.

### ISSUE THREAD

**Issue by TristisOris** [MonkAlex/MangaReader#117]
уже который раз пытаюсь обновить мангу, вместо этого, видимо, программа заново ее скачивает.

![default](https://user-images.githubusercontent.com/1270117/44079498-eb512e40-9fb1-11e8-913b-c2dba9e1d9b8.png)

перед этой попыткой была сделана архивация, в процессе снова появились первые 10 томов и все. дальше загрузка блокируется на некоторе время, т.е. при обновлении скачалось меньше, чем у меня уже есть.

проблема только с этой http://mintmanga.com/dorohedoro
остальные крупные обновляются как задумано.

**Comment by MonkAlex** [comment]
А ошибки в логе есть? Просто если не скачана одна конкретная глава (в этих томах), то на второй попытке она снова попытается скачаться, и так это и будет выглядеть.

**Comment by TristisOris** [comment]
нет. причем даже если не архивировать папки, он каждый раз заново все пытается скачать, ну и тут зависит как загрузку заблокирует сервер.
![default](https://user-images.githubusercontent.com/1270117/44088023-5cb4d542-9fca-11e8-851b-a66954989454.png)

может на сайте что изменили, раньше вообще не блокировалось. эта манга единственная, которую не могу докачать.

**Comment by MonkAlex** [comment]
По возможности, выложи storage.db, хочу посмотреть, что он по этой манге выкачивает.

**Comment by MonkAlex** [comment]
@TristisOris скачал локально, все качается на ура и повторно не перекачивается. Всё таки, если в логе есть ошибки скачивания, то при повторном запуске эти самые главы с ошибками перекачиваются.

ПС: в целом, ридманга и минтманга ограничивают частые запросы (почему и пишется про задержку в 4 минуты), можно просто попробовать позже скачать.

**Comment by TristisOris** [comment]
так позже он и начинает заново и успевает 8-10 глав перекачать.
может есть какая-то верификация готовности архивов? а тк изначально докачать не удалось, он не считает архивы скаченными.

[storage.zip](https://github.com/MonkAlex/MangaReader/files/2288167/storage.zip)

**Comment by MonkAlex** [comment]
Хм, судя по базе - ни одной успешной попытки скачивания, всмысле ни разу не было завершено хоть как то. Странно, и не проявляется.

В архивы просто упаковывается что скачано, верификации нет. По идее, если ошибок при скачивании нет, ожидается, что скачано всё целиком и архивы "готовы".

Попробуй всё таки скачать и если не скачается - приложи ещё лог, посмотрю, что там.

**Comment by TristisOris** [comment]
тогда формально каждая попытка это ошибка - он не может загрузить и я закрываю клиент, чтобы прервать процес попыток. может поэтому и повторяется?

кстати, загрузка же многопоточная? может добавить настройки для менее агрессивного скачивания. тогда и блокировать не должно будет.

[MangaReader.20180814.log](https://github.com/MonkAlex/MangaReader/files/2288465/MangaReader.20180814.log)
[storage.zip](https://github.com/MonkAlex/MangaReader/files/2288459/storage.zip)

**Comment by TristisOris** [comment]
кстати отчет о загрузке появился в логе только после закрытия и открытия программы заново.
т.е на ходу (после первого закрытия) лог не пишется.

**Comment by TristisOris** [comment]
блокировка чет около часа, так что проще будет оставить ее открытой на весь день, по частям и скачает. завтра тогда так и сделаю.

**Comment by MonkAlex** [comment]
Блокировки с разным временем бывают видимо, мне попадались и в 5-7 минут и в 15-20. Часовых пока не было, не знаю от чего зависит.

**Comment by TristisOris** [comment]
да, скачалось в итоге. вобщем нельзя прерывать загрузку.
