### ISSUE TITLE
Откат истории

### ISSUE THREAD

**Issue by ftugit** [MonkAlex/MangaReader#118]
Привет. Случился форс мажор и я форматировал диск где была софтина. Получается бекап настроек и БД у меня есть, а самой манги у меня за месяц-два нету. Подскажешь как лучше подчистить базу дабы перекачать мангу от энного числа?

**Comment by MonkAlex** [comment]
В БД можно посмотреть, какие обновления были с любой даты:
```
select * from MangaHistory
where Date > '2018-09-18 08:53:10'
```
Ну и, если всё правильно отобразится - просто делаешь `delete ` вместо `select`

После этого в принципе запускаешь и обновлять пытаешься - должно перекачать.

**Comment by MonkAlex** [comment]
Обновил скрипт, признак скачивания сейчас хранится по разному

**Comment by ftugit** [comment]
Спасибо, посмотрим. У меня была довольно старая версия. Посмотрим какой из SQL будет верный.

**Comment by MonkAlex** [comment]
Для БД достаточно http://www.sqliteexpert.com/download.html

**Comment by ftugit** [comment]
Я adminer привык юзать. Мне хватает и его.

**Comment by ftugit** [comment]
PRAGMA foreign_keys=off;

Иначе не удаляется содержимое Chapter

**Comment by MonkAlex** [comment]
Хм, главы страницы содержат, где то по дате не совпало что ли.
Ладно, помогло - и здорово =)
