### ISSUE TITLE
Запуск свернутой версии

### ISSUE THREAD

**Issue by ftugit** [MonkAlex/MangaReader#119]
Если включить в настройках, что бы софтина **запускалась** свернутой, то софтина не запускается вообще. В фоне висит. Удалить файл settings.json, то проблема решается, ~~логично~~.
Младшая версия, номер который я не помню, работа прекрасно с данной опцией.

Весь лог файл выглядит так:
```
2018-09-26 21:39:58.5105 4480 1 1.46.4.17 Debug 
2018-09-26 21:39:58.5496 4480 1 1.46.4.17 Debug             *** Initialized ***           
2018-09-26 21:39:58.5496 4480 1 1.46.4.17 Debug 
2018-09-26 21:39:58.5516 4480 1 1.46.4.17 Info Версия приложения - 1.46.4.17.
```

**Comment by MonkAlex** [comment]
Хм, в этом ничего не трогал в последних версиях. Иконки в трее тоже не появляется?
ПС: у себя проверил - всё в порядке. Надо подумать, где тут проблему и как искать, раз в логах чисто.

**Comment by ftugit** [comment]
Иконки в трее нету. Только процесс в фоне который не жрет CPU и есть пару мегабайт ОЗУ.

**Comment by ftugit** [comment]
Если необходимо, могу попробовать разные версии софтины вплоть до решения проблемы.

**Comment by MonkAlex** [comment]
Попробуй, если не сложно. Оно и добавлено то было только что в предыдущем релизе:
https://github.com/MonkAlex/MangaReader/releases/tag/1.45.5.26

**Comment by ftugit** [comment]
Версия 1.45.5.26 запускается в трее.

**Comment by MonkAlex** [comment]
Нашел причину. Починю, но хз когда выложу.
ПС: чтобы самому не забыть - поиск обновлений с запуском в трее устраивает дедлок, подвело меня постоянное отключение обновления при разработке.

**Comment by MonkAlex** [comment]
Если трей нужен - да. Либо, можешь отключить проверку обновлений - тогда в трее будет запускаться.

**Comment by ftugit** [comment]
Оки, отключу проверку обновлений. Все равно она у меня только один раз в жизни сработала.
