### ISSUE TITLE
Проект жив или мертв?

### ISSUE THREAD

**Issue by ftugit** [MonkAlex/MangaReader#120]
Пока манга-чан работает я счастлив, но судьба проекта мне более чем интересна.
Вроде UI делали новый.

**Comment by MonkAlex** [comment]
В ноябре планирую выкатить альфа версию, проект жив.
Просто пока сайты все действительно работают, активно пилить смысла маловато.
ПС: разве что добавление других сайтов могло бы активизировать меня, но я хз какие сайты, сам больше ничего почти не читаю.
