### ISSUE TITLE
Avalonia?

### ISSUE THREAD

**Issue by ftugit** [MonkAlex/MangaReader#133]
1. Отображение консоли можно убрать? ибо закрытие консоли закрывает и саму софтину.
2. Верни контекстное меню. Кнопки внизу долны отвечать за весь контент. Постеры выбранные в некотором к-ве через ctrl тоже долны управляться через контекстное меню.
Если не брать множественного выбора во внимание, то наличие контекстное меню оправдано и в сенсорных устройствах.
3. А где автозагрузка? А запуск в трее?
4. Автообновление переехало вместе со старой базой, но самой настройки я не нашел.
5. А какая манга обновляется? По консоли можно понять, но в нормальной реализации следует добавить прогресс-бар в постер или под него. Например это может прогресс бар либо % с иконкой которая даст понять, что это за цифры.
6. Я не гений в UI и мои умения ограничиваются html и js, но я определенно помню, что нормальный тоном будет менять курсор мыши на pointer, а не только фоновое выделение для постера и обводка для кнопок.
7. Если появились свойства где отображается место загрузки, то, вероятно, имеет смысл сделать поле редактируемым и рядом кнопку открытия папки.
8. grid кривой? К чему оставлять лишнее пространство если постер не влезает? Как вариант растягивать постеры или центрировать контент.
9. Вместо border лучше делать фоновую заливку. Поисковую строку вместо позиционирование лучше отделить отдельным блоком дабы поиск не накладывался на постеры.
10. Сделать возможность выбора отображения блоками, списком и гибрида:
У списка и гибрида можно добавить опционально свойства как у проводника windows которое там называется "область просмотра".
Гибрид это постер + название + мелкие сведения аля последняя глава на сайте или cкаченная. Это как список, только имеется мелкий постер слева.
У блоков можно опционально скрывать названия или отображать при наведении.
11. Нажатие на постер в поиск или в локальном списке должен открывать свойства. Можно сделать универсальным для обоих случаев.
12. Свойства у тебя это общая информация, а не только редактирование из чего следует, что нужно менять логику работы:
Любая информация типа названия, жанров, автора и т.д. пусть будет там, а вот информация о местонахождении в файловой системе, своё название и смена источника следует сместить в отдельное окно редактирования.
Ссылка в основном окне свойств может находится около названия в виде иконки ссылки.

Для UI могу сделать html образец если нужно.

Я не заметил в поддерживаемых платформах android или других клиентах из чего следует, что не нужно делать окно в окне, а добавить в качестве свойств, настроек отдельное окно. Если такой возможности нет, то кнопку возврата назад. Сейчас у тебя создается новый пункт в меню, но, если честно, мне немного не логично возвращаться назад через раздел ибо на сайтах используется браузерное "назад", а в нормальных полноценных программах окна.

**Comment by MonkAlex** [comment]
Пиши всё что раздражает.
Сейчас это очень сырая альфа, многое буду обкатывать, особенно в плане интерфейса.
Настройки реализованы не все, да.
ПС: отвечу подробно завтра уж.

**Comment by MonkAlex** [comment]
1. С консолью я пока в раздумьях. С большей вероятностью в ближайшем билде уйдет. Тут минус в том, что я пока не разобрался, что делать например с macOS, где только через консоль нашел вариант запуска самого приложения. Чисто на Windows - да, можно отключить. Оформил отдельно на подумать - #134
2. В далеком будущем планируются попытки поддержки андроида и ios, там аналогом будет разве что долгий тач, что меня лично смущает. В целом - можно наверно сделать контекстные меню, посмотрю. В Avalonia с ними были какие то проблемы, не факт что заведется.
3. По трею сделаю, но не знаю когда, постараюсь не тянуть - #121. Автозагрузка - речь про возможность скрывать в трей при запуске? Зависит сразу от трея опять таки. И тут главная проблема - хочется чтобы работало более менее единообразно на win & linux & mac. И если на маке я думаю вопрос с треем решаем, то на линуксах совсем каша. Посмотрим, возможно сделаю всё пока для винды а остальное на потом.
4. Автообновление чего? Всей манги по расписанию? Так оно в настройках первым пунктом вроде.
5. Ага, в текущем виде совсем не понять. Была идея добавить прогресс-бар под обновляемой хотя бы мангой, но пока не знаю как будет лучше смотреться.
6. Совсем не понял, если честно. Сейчас выделение манги не делает совсем ничего кроме самого выделения, а значит менять курсор вроде не особо и надо.
7. Редактируемым - врядли, оно сейчас вычислимое -- настройки манги + название манги. Кнопку - надо бы, постараюсь.
8. И грид кривой и пока не знаю, как лучше построить всё это.
9. Тоже не понял. Я ваще не сильно хорош в интерфейсах =)
10. #135 Вынес отдельно. Надо обсуждать крутить и смотреть что получится. В целом согласен, да.
11. В поиске - можно сделать, ибо там кроме свойств и открывать то нечего. В общем списке - не факт. На эту тему есть #124 и собственно противоречит текущему поведению в основном клиенте -- там открывается папка. Правда, я про даблклик. Обычный клик мышью я бы не стал делать действием, т.к. это выделение в текущей схеме.
12. Очень спорно. Текст и картинку я добавил фактически для одной вещи - чтобы легко опозновать мангу и отличать их от похожих. Делать их отдельным окном - совсем не хочется.
При этом, у кучи манги текста почти нет, не все заморачиваются с описаниями. И свойства, которые можно редактировать пока вполне вмещаются в одно окно с текстом и картинкой.

ПС: если есть какое то видение UI, которое хочется получить - можешь попробовать нарисовать в любом виде, хоть HTML, хоть в пейнте. Я правда не гарантирую, что сделаю как нарисуешь и что получится сделать хоть что-то из этого. Ещё раз - я реально слаб в дизайнах и делаю многие вещи первый раз =)

ПС2: да, в далеких планах есть планшеты-телефоны, а потому окна - не лучшая идея. Может стоит подумать над навигацией "вперед-назад" в конкретных окнах, не знаю пока.

ПС3: я вынес пару багов из этого обсуждения -- #134 и #135, как минимум их лучше обсуждать там.
Всё что ты описал в любом случае не влезет в один мой релиз, я достаточно загружен на работе, а тут прилично мелочей, которые стоит причесывать. Поэтому, если на какие то темы хочешь отдельно попереписываться - можешь их тоже оформлять отдельно. Когда всё в одной теме, плюс много переписки - очень сложно понять, закончил в итоге с этой темой или нет.

**Comment by ftugit** [comment]
Когда будет время, сделаю html набросок и подниму отдельные обсуждения за каждым пунктом если оно того будет требовать.
ps: если хочешь сделать android версию, то имеет смысл с самого начало делать под неё и уже сверху накладывать эмулятор, имхо. я не шарю как текущий дизайн должен будет на android быть ибо очень не продумано всё.
