### ISSUE TITLE
Горячая клавиша

### ISSUE THREAD

**Issue by ftugit** [MonkAlex/MangaReader#136]
Ctrl и Shift поддерживаются, а чем Ctrl + A провинился?

**Comment by MonkAlex** [comment]
Вручную ни одного хоткея не обрабатываю, всё из коробки что есть, то и работает.
Речь про Avalonia? Уточню у ребят, какого фига =)

**Comment by MonkAlex** [comment]
На стороне Avalonia сделал, постараюсь в ближайший релиз включить тогда.
