### ISSUE TITLE
Не обновляет

### ISSUE THREAD

**Issue by kyper999** [MonkAlex/MangaReader#147]
Пару дней назад обнаружил, вроде что-то с базой. 
база
[https://yadi.sk/d/8LglilibHwpz5g](url)
лог
[Новая папка.zip](https://github.com/MonkAlex/MangaReader/files/3845975/default.zip)

**Comment by MonkAlex** [comment]
Да, по логам проблема ясна.
Починю в ближайшее время и выкачу фикс.

**Comment by MonkAlex** [comment]
Внезапно, на твоих объемах местами хорошо так тормозит.
Что смогу - поправлю или хотя бы добавлю отображение того, что происходит.
Постараюсь не затягивать.
