### ISSUE TITLE
проблема со скачиванием глав

### ISSUE THREAD

**Issue by kyper999** [MonkAlex/MangaReader#150]
Привет. Не знаю с чем связано, но наверно с 27.02 с утра вместо jpg-глав качает jpg-файлы размером 109Кб. Я пробовал на разных пк и распаковывал с нуля с рабочей базой. И сейчас не знаю это сайт или с базой беда
readmanga - mintmanga
Сейчас затестил "скачать сначала", количество глав и файлов в главах вроде совпадает, но все файлы 109Кб, и лог пустой

**Comment by MonkAlex** [comment]
Буквально вчера скачивал - ещё работало.
Сейчас проверил - да, качает не то. Поправлю сегодня и выпущу билд.

**Comment by MonkAlex** [comment]
Релизнул 1.49.5.32, должно работать.
