### ISSUE TITLE
Проблема с добавлением из https://manga-chan.me

### ISSUE THREAD

**Issue by kyper999** [MonkAlex/MangaReader#158]
Добрый день.
Проблема с добавлением манги из https://manga-chan.me
Авторизовался нормально и список из избранного загрузился весь. Но при нажатии добавить из списка избранного или просто ссылкой, окно добавления зависает и не реагирует на нажатия, при это манга в списке обновляется по расписанию. Закрывать приходится через диспетчер задач. На пустой базе тоже самое.
2020-09-02 10:23:19.6753 2176 16 1.49.9.62 Debug Finish load bookmarks from 'https://manga-chan.me/'.
2020-09-02 10:23:23.4869 2176 1 1.49.9.62 Debug Command 'Добавить' started.
2020-09-02 12:18:18.9527 2176 1 1.49.9.62 Error System.ComponentModel.Win32Exception (0x80004005): Недостаточно квот для обработки команды
   в MS.Win32.UnsafeNativeMethods.PostMessage(HandleRef hwnd, WindowMessage msg, IntPtr wparam, IntPtr lparam)
   в System.Windows.Interop.HwndTarget.UpdateWindowSettings(Boolean enableRenderTarget, Nullable`1 channelSet)
   в System.Windows.Interop.HwndTarget.UpdateWindowPos(IntPtr lParam)
   в System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   в System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   в MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   в MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   в System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   в System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   в System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   в MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
System.ComponentModel.Win32Exception (0x80004005): Недостаточно квот для обработки команды
   в MS.Win32.UnsafeNativeMethods.PostMessage(HandleRef hwnd, WindowMessage msg, IntPtr wparam, IntPtr lparam)
   в System.Windows.Interop.HwndTarget.UpdateWindowSettings(Boolean enableRenderTarget, Nullable`1 channelSet)
   в System.Windows.Interop.HwndTarget.UpdateWindowPos(IntPtr lParam)
   в System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   в System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   в MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   в MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   в System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   в System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   в System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   в MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)

**Comment by MonkAlex** [comment]
Странно, у себя я повторить не смог.
Есть похожая проблема у любого приложения на винде, насколько я понимаю (https://github.com/dotnet/wpf/issues/137), но зависит от конкретного компьютера видимо. Не очень пока вкурил порядок, кто-то пытается стучаться в программу или из неё спам идёт.
Проблема проявляется сразу после запуска? Полный лог можешь скинуть?

**Comment by kyper999** [comment]
[MangaReader.20200902.log.zip](https://github.com/MonkAlex/MangaReader/files/5162040/MangaReader.20200902.log.zip)

**Comment by MonkAlex** [comment]
Судя по логу, скорее ошибка была записана в момент когда убил процесс в диспетчере.
На "добавить" может зависать, если сайт не отвечает толком, но вроде со стандартными таймаутами в 60 секунд.

Если сейчас попробовать какую-то мангу добавить, всё равно зависает? Подожди хотя бы 5 минут, можно попробовать сворачивать-разворачивать если зависнет.

**Comment by kyper999** [comment]
После того как нажимаешь добавить, вообще не реагирует ни на что, только кнопки мигают. 
Программа стоит на удаленном виртуальном сервере, Win2012R2
Напиши свою почту на kyper999@yandex.ru я скину данные для подключения
там сейчас чистая база стоит с логином к manga-chan.me

**Comment by MonkAlex** [comment]
Хм, то что сервер удаленный, может быть важно. На серверах не тестировал от слова совсем =)
На почту написал.

**Comment by kyper999** [comment]
Раньше manga-chan.me не пользовался, поэтому даже не знаю, это только сейчас вылезла эта ошибка или раньше тоже не работало. Вчера на сайте ошибка MySQL вылезала, поэтому я сначала на сайт подумал

**Comment by MonkAlex** [comment]
Проблему нашел. 
Связана с первой авторизацией с новыми логином и паролем, конкретно на сайтах manga-chan и henchan.
Починю на неделе, думаю.

Если убрать логин и пароль из настроек, должно работать. При этом, будет работать ввод логина пароля в окне именно добавления манги.
