### ISSUE TITLE
ошибка скачивания manga-chan.me

### ISSUE THREAD

**Issue by kyper999** [MonkAlex/MangaReader#172]
только установленная программа и чистая база, добавил только логин и пароль от сайта
причем некоторые изображения скачиваются
хотел через прокси попробовать, но не понял в каком формате должен быть прокси, программа мне ошибку выдала (использовал с портом)

2022-03-12 17:45:50.2846 21004 9 1.51.4.19 Error Загрузка https://img6.manga-chan.me/manganew/-6new/i/1600647724_its_useless_to_pretend_to_be_sleeping_v1_ch_5/p006_006.jpg не завершена. Использованы настройки прокси Parent
System.Net.WebException: Запрос был прерван: Не удалось создать защищенный канал SSL/TLS.
   в System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   в System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   в MangaReader.Core.Services.DownloadManager.<DownloadImage>d__5.MoveNext() в C:\projects\mangareader\MangaReader.Core\Services\DownloadManager.cs:строка 45
2022-03-12 17:45:50.2846 21004 9 1.51.4.19 Error https://manga-chan.me/online/642979-its_useless_to_pretend_to_be_sleeping_v1_ch_5.html
System.Exception: Restart download, downloaded file is corrupted, link = https://img6.manga-chan.me/manganew/-6new/i/1600647724_its_useless_to_pretend_to_be_sleeping_v1_ch_5/p006_006.jpg
   в MangaReader.Core.Manga.MangaPage.OnDownloadFailed() в C:\projects\mangareader\MangaReader.Core\Manga\MangaPage.cs:строка 120
   в MangaReader.Core.Manga.MangaPage.<Download>d__44.MoveNext() в C:\projects\mangareader\MangaReader.Core\Manga\MangaPage.cs:строка 104
2022-03-12 17:45:50.2846 21004 14 1.51.4.19 Error Не удалось скачать изображение https://img6.manga-chan.me/manganew/-6new/i/1600647724_its_useless_to_pretend_to_be_sleeping_v1_ch_5/p006_006.jpg со страницы https://manga-chan.me/online/642979-its_useless_to_pretend_to_be_sleeping_v1_ch_5.html
MangaReader.Core.Exception.DownloadAttemptFailed: Load failed after 4 counts. Download 'https://manga-chan.me/online/642979-its_useless_to_pretend_to_be_sleeping_v1_ch_5.html' to ''.
   в MangaReader.Core.Manga.MangaPage.<Download>d__44.MoveNext() в C:\projects\mangareader\MangaReader.Core\Manga\MangaPage.cs:строка 83
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   в MangaReader.Core.Manga.MangaPage.<Download>d__44.MoveNext() в C:\projects\mangareader\MangaReader.Core\Manga\MangaPage.cs:строка 114
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   в MangaReader.Core.Manga.MangaPage.<Download>d__44.MoveNext() в C:\projects\mangareader\MangaReader.Core\Manga\MangaPage.cs:строка 114
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   в MangaReader.Core.Manga.MangaPage.<Download>d__44.MoveNext() в C:\projects\mangareader\MangaReader.Core\Manga\MangaPage.cs:строка 114
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   в MangaReader.Core.Manga.MangaPage.<Download>d__44.MoveNext() в C:\projects\mangareader\MangaReader.Core\Manga\MangaPage.cs:строка 114

**Comment by MonkAlex** [comment]
Ошибка слишком общая к сожалению, про "Не удалось создать защищенный канал SSL/TLS"

Прокси могло бы быть вариантом решения. Сейчас поддерживаются только http прокси (бывают ещё socks или типа того).
Настраивается относительно легко - берешь какую то проксю и указываешь её параметры. Жмёшь кнопку "проверить", чтобы понять, всё ли норм и работает ли.
![изображение](https://user-images.githubusercontent.com/6784764/158124385-254a91db-429d-446b-b691-fd3f674b7ef2.png)

Потом этот прокси нужно указать в настройках конкретного сайта Mangachan (либо в общих настройках программы, если всю мангу надо качать через прокси).

**Comment by kyper999** [comment]
51.89.207.202:1490
Логин: kyper999 Пароль: 717ce0b8
я потом пароль поменяю
![изображение](https://user-images.githubusercontent.com/15810441/158135043-2e4576b8-af05-4d3c-a11a-cbfe625e52e4.png)

**Comment by MonkAlex** [comment]
Проверил у себя - работает и с проксей и без неё корректно.

В браузере просмотр манги работает или заблокирован роскомнадзором например?

**Comment by kyper999** [comment]
в браузере работает, и программа новая с пустой базой, сейчас попробую в этой же сети на другом пк

**Comment by MonkAlex** [comment]
Возможно разные обновления windows. 
Чисто в качестве эксперимента - проверь вариант программы который подписан как Avalonia. Там немного другой подход к сетевым соединениям, может будет работать.
