### ISSUE TITLE
Стартовая и конечная глава глава

### ISSUE THREAD

**Issue by ftugit** [MonkAlex/MangaReader#74]
Почему нельзя задать нужную главу и конечную? Какой смысл скачивать все главы.

**Comment by MonkAlex** [comment]
Все главы качаются один раз. А потом можно кликать "обновить" и скачиваются только новые.

Нужно что-то другое? Я не очень понимаю, зачем давать выбор, разве что когда их очень много... подумаю, мб добавлю в каком то виде.

**Comment by ftugit** [comment]
Я перед тем как созрел причитал одно произведение на 300 глав... а скачивать эти 300 для ностальгии желания мало. Примерно в этом смысл.
Либо если я буду не у себя дома или переустановлю ОС и надо продолжить закачку... хотя тут больше подойдет возможность импорта/экспорта истории и каталога манги.

**Comment by MonkAlex** [comment]
Импорт экспорт условно есть, достаточно сохранять файл `storage.db`

С указанием глав есть одна проблема - переводчики часто добавляют главы не в конец, а в середину - пропущенная бонусная глава, пропущенная глава т.к. переводят разные люди. Если и добавлю что-то, то оно будет довольно грубо всё пропускать видимо. Может быть, лучше пропускать не 300 глав условно, а главы, которые были до определенной ссылки на главу.

**Comment by ftugit** [comment]
В качестве примера дам скрипт http://4pda.ru/forum/index.php?s=&showtopic=131624&view=findpost&p=31135180
Там дается ссылка на мангу, скрипт парсит все главы и предлагает сделать выбор от и до. На основе это я создал данную тему.
Можно пойти вашим вариантом научить хавать ссылки типа https://acomics.ru/~freak-hospital/481 которая и будет "стартовой"(к слову говоря: такие ссылки сейчас приводят к вылету с ошибкой), но результат не изменится. В ссылки, насколько я понимаю, и так уже есть номер главы, следовательно в чем разница между "ссылки на главу" и "задать нужную главу" просто не вижу.
Да, acomics имеет возможность вставлять главы в прошлое, но как это влияет на саму нубирацию глав в url я не знаю. Могу только сказать: можно сделать как угодно, но научить качалку качать с нужной главы все же имеет смысл.

**Comment by ftugit** [comment]
То, что история хранится в storage.db уже хорошо, можно будет через Adminer покататься.
Я когда поднял вопрос про импорт/экспорт не знал о создаваемых файлах программой т.к. она была загружена в общую папку где и без данной софтины много файлов.
Учту, что в определенном смысле импорт есть. Я просто не привык к софтинам которые юзает sqlite так открыто.

**Comment by MonkAlex** [comment]
Держать в общей папке не советую, программа создает и временные файлы и логи и конфиги.

Насчет поддержки загрузки с N главы - будет, но не быстро. В феврале, надеюсь.

**Comment by MonkAlex** [comment]
Будет выложено в ближайшие пару недель наверно. 
В целом готово, надеюсь без багов.
