### ISSUE TITLE
Дополнительный источник: mangachan.me

### ISSUE THREAD

**Issue by ftugit** [MonkAlex/MangaReader#75]
Что особенного в хентай-чан который и так имеет 99% ссылок на архивы с главами, что манга-чан так был ущемлен(который часто и не имеет таковых)?

**Comment by MonkAlex** [comment]
На самом деле что угодно можно добавить, надо просто время найти. С работой времени остается не так много. К лету будет, может раньше по настроению, реально добавление занимает от силы часов 6-8.

**Comment by ftugit** [comment]
Что угодно смысла нет, в русском сегменте имеется ряд сайтов который и образует весь русский перевод. Можно в качестве альтернативы и readmanga использовать, но там нет некоторых произведений(а вот наоборот не встречал).

**Comment by MonkAlex** [comment]
@ftugit если ничего такого не случится, то на днях допишу тесты и будет релиз. Манга качается, авторизация работает, закладки подгружаются. Надо будет только проверять, не упустил ли я чего.

**Comment by MonkAlex** [comment]
Такс, будем считать что готово, если есть проблемы - будем разбираться отдельно.
