### ISSUE TITLE
Проблемы в списке при проверке новых глав

### ISSUE THREAD

**Issue by kyper999** [MonkAlex/MangaReader#76]
При проверке, когда идет по списку, доходит до определенной и сразу пишет проверка завершена. Когда исключаю пару штук (сложно определить на какой тормозит), он проходит это место и снова на определенном также. Началось с первых чисел марта. По списку не доходит даже до трети, очень много таких мест. Обновление с readmanga и mintmanga. Пиши на kyper999@yandex.ru, вышлю папку с программой. Версия программы последняя

**Comment by MonkAlex** [comment]
@kyper999 тут можно файлы прицеплять, поэтому упакуй storage.db и два лога (error.log, manga.log) в архив и прицепи тут (кнопка снизу "selecting them"). Вечером посмотрю.

**Comment by kyper999** [comment]
[log.txt](https://github.com/MonkAlex/MangaReader/files/829970/log.txt)
это .zip просто в этом расширении не хотел грузиться

**Comment by MonkAlex** [comment]
Ридманга и минтманга начали последнее время кидать "Удаленный сервер возвратил ошибку: (417)" на слишком частые запросы. Похоже, надо копать в этом направлении, буду думать. Больше, судя по логам, ничего такого не происходит.

**Comment by kyper999** [comment]
может поставить задержку в проверке на секунд 15

**Comment by MonkAlex** [comment]
@kyper999 запросов всяко много - на каждую мангу запрашивается главная страница + страница каждой новой главы. Тут скорее надо добавлять задержку исключительно при возникновении 417 ошибки. Попробую накрутить вечером сегодня-завтра.

**Comment by MonkAlex** [comment]
@kyper999 задержка, если я нигде не ошибся, аж до 10 минут может требоваться. Я попытаюсь на выходных протестировать с меньшим интервалом, но если ничего не изменится, то скачивание с ридманги\митманги сильно замедлится, особенно на больших объемах.

**Comment by kyper999** [comment]
Ошибка появляется только у некоторых. После остановки заново запускаешь, и он список быстро проходит (без ошибок) опять до этого же места, хотя сайт один и тот же. Я пробовал раз 10

**Comment by MonkAlex** [comment]
@kyper999 банится конкретная ссылка, похоже. Другие могут открыться при этом, а вот конкретно забаненная становится доступна минут через 10. Я сейчас добавил переповтор, на случай 417 ошибки, но в целом так работает пока медленнее. Проверю на полноценной нагрузке ещё, вчера на это времени не было.

**Comment by MonkAlex** [comment]
Я выкладываю релиз 1.40.3.23, проверяйте. Не факт, что реально поможет, так что отписывайтесь о результатах.

**Comment by kyper999** [comment]
Работает, не знаю проверяются или нет те, которые тормозят, но по списку до конца проходит, и все отлично проверяется. Проверял примерно час, но при автообновлении для меня это не критично.
