### ISSUE TITLE
Многопоточное скачивание

### ISSUE THREAD

**Issue by ftugit** [MonkAlex/MangaReader#79]
Я конечно не знаю как работает качалка, но нельзя ускорить процесс скачивания за счет многопоточности. Я не предлагаю качать картинки в несколько потов, я предлогаю качать сами изображения n штук за раз. Например mangachan без проблем отдает 5 изображений на одного качающего клиента после чего ошибка.
Просто я такую картину наблюдал сегодня качая одну главу я потратил 10 минут т.к. сервис слабо работал и для интереса скачал её же через download master разница была в 8 минут.

**Comment by MonkAlex** [comment]
В публичной версии количество потоков как раз таки не ограничено и качается сразу в несколько потоков. В такой ситуации с медленных сайтов программа умудряется ничего не скачать, так что в ближайшем билде будет ограничение в 25 наверно потоков скачивания. Ошибок при этом не наблюдал, но буду ещё тестировать.

DM может оптимизировать как то загрузки, поэтому будет разница в скорости.

**Comment by MonkAlex** [comment]
По возможности - error.log бы, с указанием времени и главы, которая так плохо качалась. Есть подозрение, что это я как раз и чиню последнюю неделю.

**Comment by ftugit** [comment]
Конкретно с "B Type H Style". Вес файлов даже до 500KiB не достигает.
https://rocld.com/mzab

**Comment by MonkAlex** [comment]
Да, чинил я как раз что-то подобное. Через неделю-другую будет релиз, посмотришь, поможет ли. Аналогично плохо качалось с henchan.me

**Comment by ftugit** [comment]
Оттуда я качаю архивами, они там всегда в наличии. Архивы редко когда качаются ниже 1MiB в секунду, но как бы это странно не звучало уменьшение к-ва потоков увеличивает, иногда, скорость.

**Comment by MonkAlex** [comment]
@ftugit именно это же сделал с качалкой. Качало в слишком много потоков, сервер в итоге меня отпинывал и общая скорость снижалась. Баланс ещё буду искать, может в настройки потом вынесу число потоков, посмотрим.

**Comment by ftugit** [comment]
Не самый лучший пример, но у меня android мобила не может скачивать файл в постоянной или вышей скоростью если потоков 2 и более. Возможно и есть ПК древние либо настроенные похожим образом, что пакеты урезаются для "баланса" интернет скорости(у меня у сетевой карты есть софт для винды которая по количеству запросов от одной софтины выставляет приоритет скорости и отсюда они либо "нормально" либо "низко", типо чтобы одна софтины не забивала себе весь интернет).
Отсюда возможность изменять количество потоков выглядит самым лучшим вариантом.

**Comment by ftugit** [comment]
Уточни пожалуйста, какой из пунктов верен или ближе к истине
1. Скачивание одного изображения идет в несколько сегментов.
2. Скачивание одного изображение идет в качестве первого потока, а следующие в качестве второго и т.д.

Тему я поднял под 2-й вариант, а что именно сейчас подразумевается под "многопоточность"?

**Comment by MonkAlex** [comment]
Второй. Далеко не каждый сайт умеет отдавать один файл в несколько потоков, так что второй вариант в теории выгоднее.

**Comment by MonkAlex** [comment]
Многопоточность немного причесана, плюс добавлен показатель скорости.
Так что, эту таску я считаю закрытой, @ftugit будут вопросы \ проблемы - пиши.
