### ISSUE TITLE
Счетчик скорости скачивания

### ISSUE THREAD

**Issue by ftugit** [MonkAlex/MangaReader#80]
А можно прикрутить дополнительный столбец со скоростью которой идет закачка?
В принципе это можно узнать и через "монитор ресурсов", но там смешные цифры, что даже не верится.

**Comment by MonkAlex** [comment]
Скачивание многопоточное, не уверен как правильно считать общую цифру. Разве что по отношению скачано \ потрачено времени для каждой конкретной манги.

**Comment by MonkAlex** [comment]
@ftugit какой счетчик интересует? 
1. Конкретно в данный момент времени с какой скоростью качается
2. Какая была средняя скорость у манги (в целом, с начала процесса до конца).

Почему возникает вопрос - на 100 условных файлов старт должен выжрать весь канал, а вот когда будут качаться последние файлы - скорость может и упасть, зависит от сайта. И тут цифры можно выдавать разные. Можно в конце плавно снижать "среднюю" для манги цифру, а можно показывать что скорость упала резко.

Мне больше нравится первый вариант, когда показывается именно загруженность канала, вне зависимости от того что качается.

**Comment by ftugit** [comment]
Я изначально хотел первый вариант. 2-й вариант это уже лишний функционал.

**Comment by MonkAlex** [comment]
@ftugit проверяй, как оно визуально и правду ли ваще показывает.

На моём интернете в целом почти не врёт, можно ориентироваться.

Будут проблемы - сюда же пиши или новую багу оформляй.

**Comment by ftugit** [comment]
У меня скорость часто видит на одном числе, возможно прикрутить рядом счетчик "[скачено]/[всего]"?

**Comment by MonkAlex** [comment]
В каких единицах измерения? В мегабайтах - так заранее неизвестно, сколько всего будет.
В файлах - аналогично, файлы получаются для каждой главы на ходу.
Стабильный минимум для всего, кроме акомикса - главы. Типа 6 глав из 30.
У акомикса - страницы, но смысл тот же.

Ваще, странно что скорость висит, у меня наоборот скорость сначала растёт до 3-5мб, а потом падает на самое дно и медленно тащится.

**Comment by ftugit** [comment]
Как лучше всего реализовать так и сделай. У меня скорость стоит и я как идиот иду в файлы ибо не верю с божественную стабильность. Как правильно на этом этапе я вижу либо появление новых пикчей и кучи пыстых папок либо тишину. Последнее лечится только перезапуском.

**Comment by MonkAlex** [comment]
Показатель скорости должен обновляться каждую секунду.
Если он не обновляется, то мне нужен лог файл - он или в папке программы, если это было в последний запуск или в папке logs, там по дням.

**Comment by ftugit** [comment]
https://cloud.mail.ru/public/AXYM/nuQrN5Czj

Лог я могу дать, но я сам там вижу только то, как постоянно удаляю и добавляю мангу.
Ибо каждый раз я наблюдал, как у меня лихо появляются пустые папки без отсутствия прогресса.
Пока под конец не пошел спать. К слову ПК не выключился, хотя галочка стояла.

**Comment by MonkAlex** [comment]
Хм, попробую добавить логирование более детальное, хотя есть подозрение, что просто качалось очень уж медленно.
Ну и, стоит отметить, что с минтманги качалось больше 2 часов, тоже не быстро.

У меня с мангачан иногда скорость падает до нереально низкой, толи борются так с частыми скачиваниями, толи что.

**Comment by MonkAlex** [comment]
Такс, показатель скорости действительно может повеситься, как минимум на ридманге\минтманге.
Починю.

Выключение ПК - какая винда, от обычного пользователя запущено или от админа?

**Comment by ftugit** [comment]
От кого запущена софтина не скажу ибо запускаю "как есть" и права админы выдаются автоматом при запросе софтины.

**Comment by MonkAlex** [comment]
Таки вроде опять поправлено, надо проверять.
