### ISSUE TITLE
Имена папки с мангой

### ISSUE THREAD

**Issue by ftugit** [MonkAlex/MangaReader#82]
Почему манга от readmanga(другое не проверял) имеет русское название, а mangachan английское?
Может добавить новый параметр в настройки который данную логику реализует.
Например по дефолту используется английский, а если в настройках выбрана галочка "Использовать русское название манги при наличии".

**Comment by MonkAlex** [comment]
На ридманге\минтманге названия строго делятся по языкам - ру\ен\яп. В мангачан такого разделения нет, название просто включает в себя иногда русское, а иногда нет. Выделять русское из составного пока не представляю как. Есть идеи?

Выглядит так, будто идёт оригинальное название а потом в скобках русское, могу ориентироваться на это. Правда, как интересно выглядят названия, у которых есть собственные скобки.

**Comment by ftugit** [comment]
Единственное что приходит на ум
1. проверять наличие скобок
2. отделять их отдельно друг от друга
первое до скобок всегда английский
по дефолту название английское
НО если предположить исполнение(например автор упорот и поменял их местами как бывает на хентай-чан), то через RegExp проверять наличие русских символов.

> Правда, как интересно выглядят названия, у которых есть собственные скобки.

Мы знаем что в скобках русское называние, можно просто не отсеивать данный кусок текста, а продолжить парсинг строки вплоть до содержимого скобок с русскими буквами.

**Comment by MonkAlex** [comment]
http://mangachan.me/manga/17625--okazaki-mari.html

Вот тут ваще нет другого языка, но Regex это поймает как другой язык =)

Способ нашел, попробую прикрутить.

**Comment by MonkAlex** [comment]
Так, будут русские имена. Чтобы манга приходила с русскими именами - в настройках должно быть установлено "Язык по умолчанию - Russian". Аналогично, патч через неделю.
