### ISSUE TITLE
Добавление манги во время скачивания

### ISSUE THREAD

**Issue by ftugit** [MonkAlex/MangaReader#83]
Я не могу добавить мангу на скачивание во время обновления. Получается если я нажму "пауза" по логике это прервет процесс обновления и даст возможность настроить софтину и добавить новую папку.

**Comment by MonkAlex** [comment]
Пауза была добавлена на тот случай, если скачивание забьет весь канал и не получится даже сайты смотреть никакие во время обновления.

Добавление в процессе пока технически довольно сложно, но я подумаю и попробую.

**Comment by ftugit** [comment]
А полная остановка? По логике качалка не должна скачивать заново скаченные элементы.
Получается. Я останавливаю скачивание. Делаю чёрные дела. Запускаю обновление. Качалка по логам смотрит последний скаченный файл и продолжает со следующего.

**Comment by MonkAlex** [comment]
@ftugit только acomics работает пофайлово. Остальные манги учитываются по главам. Так что главу-две в такой реализации придётся перекачать. Может и немного, а может и много.

Сюда же - сортируется сейчас по разному. Т.е. либо после остановки продолжаем с места остановки и можем пропустить добавленную, т.к. она где то вверху оказалась (а зачем её тогда добавляли?), либо с начала.

А так - да, полную остановку тоже можно сделать, думается мне. Буду посмотреть, но позже, выглядит некритичным.

**Comment by ftugit** [comment]
У меня вопрос, а как составляется список на скачивание?

**Comment by MonkAlex** [comment]
Всё, что визуально в списке видно - то и будет скачиваться.
Т.е. если пофильтровать по имени, а потом нажать обновить - обновится только найденная манга.

Сортировка по имени вроде тоже учитывается - в каком порядке в списке, в таком и должно скачиваться. Но вот тут бывают исключения, именно алфавит вроде соблюдает, а вот некоторые манги местами может менять =)

**Comment by ftugit** [comment]
Вопрос был в другом.
Как софтины собирает ссылки на главы. Когда я нажимаю "обновить"(т.е. в тот момент софтина знает, что у манги a сейчас для скачивания доступно 5 глав и скачает только их) или она качает главы до победного(типо если я качаю уже час, а минуту назад новую главу добавили, то она тоже будет скачена).

**Comment by MonkAlex** [comment]
Первый вариант. Сначала проверяется, есть ли новые главы, потом они качаются. Скачивание в том виде, в каком мангу смотрит человек (странички, одна за другой) выйдет медленнее.

**Comment by ftugit** [comment]
Получается главы которые добавили после начала обновления скачиваться не будут?

**Comment by MonkAlex** [comment]
Да. Попадут в след. обновление, всё равно не пропустятся.

**Comment by MonkAlex** [comment]
@ftugit я тут вижу пару вариантов пока:
1. Мангу можно добавлять, но она никак не влияет (и не попадает) на текущий процесс обновления. Это относительно простой вариант.
2. После добавления манги она проходит через все фильтры запущенного обновления (это фильтры вверху на панельке) и добавляется в конец текущего процесса обновления. Это вариант посложнее, но кажется тоже реализуемым.
3. Как второй, но фильтры игнорируются. Идея в том, что раз идёт добавление в процессе, то хочется скачать, а фильтры неважны. Тут будут проблемы в том, что раз фильтры игнорируются, то скачивание будет, а вот отображение добавленной в списке - нет. Дешевле 2 варианта, но визуально выглядит странно.

Первый вариант сгодится на случай, если хочется занести какую то мангу на "почитать потом", а софт сейчас занят скачиванием. Второй очевидно круче, но закидывать в обновление надо бы как то очевидно, а то например фильтр по имени стоит, добавляется манга с неподходящим именем, а потом не очевидно, почему не скачалась. Третий просто промежуточный между ними.

Если есть какие то идеи - пиши. Ну и по возможности отпиши, какого поведения ты ожидаешь.

ПС: полную остановку прям сейчас нормально не сделать, если она тебе всё ещё нужна - напиши тоже пожалуйста.

**Comment by ftugit** [comment]
У меня полная остановка выполнялась путем перезапуска софтины. Софтина вполне, вроде, успешно скачивала пропущенные файлы. Возможность оставить скачивание лишним не будет, при условии отсутствия возможности добавить "на лету" мангу.

А коли обсуждение пошло о возможности добавления сия функционала, то и функция остановки является менее, для меня, нужным функционалом.

Реализовывать можно как душе угодно. Можно использовать оба варианта, а можно только первый. Думай сам.
Оба варианта:
1. После добавления манги появляется дополнительное окно с вопросом о добавлении новой манги в текущий поток скачивания с возможность запомнить выбор для данной сессии скачивания.
2. Во время добавления манги добавить еще одну кнопку отвечающию за функцию скачивания в текущем потоке. Например "добавить" и "добавить и скачать".
Первый вариант:
Как ты и сказал это является самым простым вариантом, но пользователю стоит об этом сообщить. Я то может и буду знать о сия "фичи", а другой человек не будет. После будет удивляться. Ведь вспоминая файловые качалки они качают файлы в любом случае, а не только те, что были добавлены до нажатия "скачать".
Другой вариант:
Это реализации возможности остановки скачивания с последующим добавлением.

Если честно лучше бы манга качалась по иным, чем сейчас принципам. Как в обычном файловом менеджере. Добавил ссылку и она скачается сразу. Если сортировка по имени, но манга попала выше, чем текущая позиция для скачивания, то качается файл выше после завершения скачивания текущей. Главы которые будут качаться определяются в момент начала скачивания, а не на этапе старта.
Я понимаю, что выше описанное, это переделывание скрипта, вероятно, целиком. Следовательно я оставлю данный текст на случай если ты задумаешь переосмыслить скрипт на корню(может из-за смены языка программирования или просто новый виток жизни софтины). Всё, что я говорил ранее о обновляемых парсерах тоже следует включить в мысль выше, а не переделывать скрипт ради них...

**Comment by MonkAlex** [comment]
@ftugit 
>Главы которые будут качаться определяются в момент начала скачивания, а не на этапе старта.

Главы определяются в момент старта конкретной манги.
Т.е. если 100 штук запущено на обновление, то последняя (100) проверит новые главы только в самом конце, когда 99 будет скачана, а не в начале.

В целом, возможность добавления манги сделал. Сделал самую простую - тупо добавляется на скачивание. Могут быть баги, но вроде проверил.
