### ISSUE TITLE
Выключение компьютера по завершению обновления

### ISSUE THREAD

**Issue by ftugit** [MonkAlex/MangaReader#84]
Берем любую качалку хоть немного популярную и они все имеют возможность выключить ПК, отправить в сон и т.д. по завершению скачивания. А чем мы хуже?

**Comment by MonkAlex** [comment]
Выключать компьютер прям при каждом обновлении врядли захочется, поэтому мне интересно - где эта настройка видится и как она должна включаться\выключаться?
Например:
1. Запускаю обновление
2. Появляется галочка снизу "выключить ПК по завершению"

Или ещё:
1. В настройках добавляется галочка "Выключать ПК по завершению обновления"
2. Нажимаю обновить
3. ПК выключается автоматически после обновления (выглядит стремно, хм-хм)

**Comment by ftugit** [comment]
Скорее первый вариант. Только галочку надо ставить вручную. По завершению обновления программа, при возможности, вырывается вперед(как диспетчер задач с "поверх окон") и запускает таймер на 10 секунд с возможностью отменить процесс.

**Comment by MonkAlex** [comment]
Звучит неплохо. Не обещаю быстро, но к лету наверно сделаю.

**Comment by MonkAlex** [comment]
Вот так выглядит Download master например:
![default](https://cloud.githubusercontent.com/assets/6784764/25707511/cb51576e-30f4-11e7-8090-bc3044ea601d.png)

**Comment by MonkAlex** [comment]
uTorrent, мне нравится больше.
![default](https://cloud.githubusercontent.com/assets/6784764/25707729/83cef5b2-30f5-11e7-9a16-626e7d69e47a.png)

**Comment by ftugit** [comment]
Я за любую реализацию

**Comment by MonkAlex** [comment]
Как то так вышло.
Окно пытается выскакивать поверх всего, но гарантировать не буду.
![default](https://cloud.githubusercontent.com/assets/6784764/25770576/cbad00cc-3249-11e7-9645-b7bca2e691f3.png)

**Comment by MonkAlex** [comment]
Полноэкранные игры не дают отобразить панельку нормально, а вот плеер с видео - вполне.
Так что будет в ближайшем релизе.

**Comment by ftugit** [comment]
Попробуй в полноэкранном режиме запустить диспетчер задач поверх окон. Думаю нечего хорошего не выйдет.
