### ISSUE TITLE
Не могу добавить мангу после обновления

### ISSUE THREAD

**Issue by ftugit** [MonkAlex/MangaReader#86]
Обновился и не могу добавить мангу.
Ссылка на логи с момента запуска и ошибки с вылетом:
https://drop.me/BymDGB

**Comment by ftugit** [comment]
Переустановка софтины(если можно так выразится) помогла решить проблему.

**Comment by ftugit** [comment]
Не буду создавать новый вопрос, и вот ссылка
https://drop.me/B4kKWM

тупо велет софтины во время обновления.

**Comment by MonkAlex** [comment]
По первой ошибке - манга уже есть в списке, судя по ошибке. Надо проверять конечно, но выглядит именно так.
По второй - вечером уже только гляну, выглядит подозрительно, похоже это я перемудрил со скачиванием в последней версии где то.

**Comment by ftugit** [comment]
манга была, но с другого ресурса и  под другой папкой

**Comment by MonkAlex** [comment]
По первой ошибке - папка действительно не проверялась, починил. Падать больше тоже не будет на этом.

По второй - в 71 главе манги сдохла первая картинка. С одной стороны, падать на этом явно не стоит и я починю. С другой - стоит ли считать такую главу скачанной - непонятно.

**Comment by ftugit** [comment]
Лучше вообще не скачивать главу и пусть читатель обойдется. Обо всех нескаченных картинках можно сообщаться при следующем включении софтины(на случай введения выключения ПК по окончанию синхронизации) и/или по завершению обновлению.

**Comment by MonkAlex** [comment]
Нормального информирования пока не будет, тут надо продумывать целиком, как бы сделать нормальный визуальный лог, с отображением прогресса и ошибок.

Падать на этом больше не будет, при повторном запуске - будет попытка снова перекачать.

Релиз выйдет не скоро наверно, если сильно мешает - отпиши, выпущу пораньше, но только с этим исправлением.

**Comment by ftugit** [comment]
Я уже говорил как часто обновляю мангу? В ближайший месяц-два я софтину не запущу(примерно столько и постов от меня не будет, ляпота).
