### ISSUE TITLE
Не сохраняет настройки

### ISSUE THREAD

**Issue by ftugit** [MonkAlex/MangaReader#87]
При попытке сохранить вылетает это:
https://i.yapx.ru/HR4X.png

После закрытия софтины она пропадает из трея, повторный запуск возможен только ручным убиваем процесса.

**Comment by ftugit** [comment]
Перезапуск помог решить проблему настроек, но магия, блин.
Я так и не понял причем тут манга которую я только скачал

**Comment by MonkAlex** [comment]
Если это было одновременно с предыдущей ошибкой, то это всё та же фигня с тем, что такая манга уже была в программе. И он пытается существующую переместить из старой папки в новую, хотя это и невозможно. Сложная ерунда короче, перезапуск если полечил, то и бог с ним.

Скорее всего, это проблема миграции с абсолютных путей на относительные, больше этой фигни быть не должно.

**Comment by ftugit** [comment]
эта ошибка возникла после "лечения" предыдущей
