### ISSUE TITLE
Удаление манги

### ISSUE THREAD

**Issue by ftugit** [MonkAlex/MangaReader#88]
Удалил я B Gata H Kei которая насчитывает овер дохера глав и долгое зависание...

Если удаляется история и все связанное с мангой, то может имеет смысл:
1. добавить окно которое говорит: "Удаление манги, ожидайте".
2. удалять из меню пункт с мангой и уже в фоне(да хоть в отдельном процессе) удалять все остальное.
3. не удалять историю вообще на случай восстановления манги в список(ну не хочу я пока читать её). получается если ссылку на неё вновь внесут то появится вопрос мол восстановить историю.
4. спрашивать удаление истории и комбинировать с 3-м пунктом и 1 и/или 2.

если брать 3 и/или 4 пункт, то можно ввести новый раздел "удаленные".

далее, по возможности снимать мангу из списка автоматически если она была "завершена" в плане перевода. предварительно можно уведомить пользователя или спросить о сия действии.

не проверял в действии, но добавить окно с возможностью удалить и файлы манги.

- [x] Асинхронное удаление, чтобы не вешалось всё приложение
- [ ] Выборочное удаление истории (спорно)
- [x] Выборочное удаление файлов манги (надо бы)

**Comment by MonkAlex** [comment]
В целом всё за. Не понял только 

> по возможности снимать мангу из списка автоматически если она была "завершена" в плане перевода

снимать - это что делать? Не пытаться обновлять? Снять признак "Обновлять" можно, подумаю над этим.

**Comment by ftugit** [comment]
в целом я имел введу если манга переведена, то больше не тратить ресурсы и место в списке, а сразу убрать её из списка на "обновление" или по запросу.

**Comment by MonkAlex** [comment]
@ftugit тут есть проблема с тем, что на той же ридманге статус переведено\завершено не гарантирует, что обновлений не будет. Иногда добавляются бонусные главы, иногда ещё что-то. Сомнительно.

**Comment by MonkAlex** [comment]
Удаление с сохранением истории всё таки делать не стал.
Не хочется читать - отмечаешь "не обновлять" и всё.

А так - удаление больше не будет вешать клиент.
Ну и добавилась возможность удалить всю папку с мангой.
