### ISSUE TITLE
API софта

### ISSUE THREAD

**Issue by ftugit** [MonkAlex/MangaReader#91]
Есть некий способ общения с софтом?
Хочу запилить для себя автоматическую синхронизацию с моей БД.

Не, как вариант можно отслеживать изменение storage.db, но это грубый метод.

**Comment by MonkAlex** [comment]
Сложный вопрос.
А чего именно хочется и как планируется выполнять подключение?

Просто код то открытый, а апи... у меня не сервис, чтобы было прям нормальное публичное апи с продуманными запросами\ответами.

**Comment by ftugit** [comment]
Меня интересовала возможность ответа от софтины через, например, cmd. Любое возможное API которое сможет локально обрабатывать PHP.
Если API по дефолту нет, то и не заморачивайся. Я просто напишу скрипт для работы с твоей БД и в ручную буду отправлять обновление.

**Comment by ftugit** [comment]
![default](https://cloud.githubusercontent.com/assets/17074693/26524515/83dd9fd6-433d-11e7-85eb-f7821443ef6b.png)
Кстати, спасибо за выключалку. Через часов 6 и проверим как ПК выключится))

**Comment by MonkAlex** [comment]
Апи есть конечно, но оно все на c# и как его к ПХП прикрутить - абсолютно без понятия.

Ладно, я тогда закрываю, раз самостоятельно разберешься.

ПС: буду надеяться, что выключится нормально =)
