### ISSUE TITLE
Как насчет ввести новые фичи?

### ISSUE THREAD

**Issue by ftugit** [MonkAlex/MangaReader#93]
Я знаю, что дехера охеревший и зае... надоел уже тебе, а нельзя добавить поддержку ctrl и shift т.е. выделение нескольких позиций сразу? Дабы обновлять и удалять можно было проще, а не по одному.

+ сортировку: по имени, по дате обновления, по дате добавления.

Еще одно, почему софтина к названием папкам добавляет точку перед " ' "?
Например: "Lilith's Cord" в "Lilith.'s Cord"

Я реальное охеревший... жопой чую, что софтина "для себя", а тут я нарисовался.

**Comment by MonkAlex** [comment]
Ну, во первых софт для всех, иначе чо бы я его ваще выкладывал =)

Сортировка по имени есть, кликнуть надо просто по колонке. По остальным - а нахрена оно надо?
Мультиселект делать влом, хочется много - кликни "обновить всё" и забудь. Позже будет, но сильно позже, я переделывать интерфейс планирую.

Точка в имени скорее всего старый косяк и должно в свежей версии после обновления её убрать. Обновить надо конкретно нужную мангу, вроде было там где то переименовывание манги и папки автоматическое.

**Comment by ftugit** [comment]
Мне удобнее не по названию, а по дате добавления из-за этого и прошу, дабы новое было последним. Особенно удобно когда только добавил и не искать мангу среди множетва."
"Обновить всё" подходит только при условии когда времени не жалко... если планируешь вводить новый интерфейс надеюсь он будет сразу с поддержкой энного.

Сегодня обновился и проверю "пропажу" точки в следующих обновлениях.

**Comment by MonkAlex** [comment]
>Особенно удобно когда только добавил и не искать мангу среди множества.

Окей, вот это - аргумент.

**Comment by MonkAlex** [comment]
@ftugit сортировка будет в ближайшем релизе. 
Правда, только в настройках, т.е. на лету не меняется, но я думаю не сильно и надо такое.

Насчет выделения манги пачкой - подумаю и попробую.
