### ISSUE TITLE
"Сворачивать в трей"

### ISSUE THREAD

**Issue by ftugit** [MonkAlex/MangaReader#94]
1. Софтину добавил в автозапуск.
2. Софтина запускается без видимого окна.
3. Софтина висит в панели задач.
4. Софтина уходит "в трей" только при ручном нажатии на "свернуть".

**Comment by MonkAlex** [comment]
Не обещаю быстро, но в целом звучит неплохо.

**Comment by MonkAlex** [comment]
Ну, сейчас сворачивание работает только после запуска.
До этого есть как минимум два окна, с которыми надо решать что делать:
 - настройки могут ругаться, что не найдена папка, куда качать мангу
 - предложение обновиться может выскочить

В режиме, когда запускается в трей, я не уверен, стоит ли это отображать.

Плюс, опять таки вопрос, достаточно запускать в трей или делать прям автозапуск через реестр\папку автозагрузки.

**Comment by ftugit** [comment]
1. Зачем обновляться при наличии ошибок? Уведомить пользователя средствами windows центра уведомлений.
2. Я только включил обновление раз в n часов и если такая хрен всплывает, то толку от автообновления?
3. Если учесть, что софтина имеет разряд "компактная" то лучше это делать через автозапуск-папку.

**Comment by MonkAlex** [comment]
1. Не понял к чему это. Обновляться стоит всегда. Центр уведомлений виндовс - хз что такое, у меня Win7 ваще, тут такой ереси нет.
2. Раз в N часов работает в любом состоянии, добавить запуск сразу в трей ему не помешает, тут согласен.
3. Папка или реестр - разницы никакой.

**Comment by ftugit** [comment]
1. "настройки могут ругаться, что не найдена папка, куда качать мангу"
3. Имеется. Софтина не имеет файла-удаления и следам автозапуска будет проще всплыть.

**Comment by MonkAlex** [comment]
Такс, ну в теории тоже будет в ближайшем билде.
Прямо таки автозапуск пилить стало лень, а вот запуск сразу в трей - сделал.
