### ISSUE TITLE
Точки в главах

### ISSUE THREAD

**Issue by ftugit** [MonkAlex/MangaReader#97]
Долго я терпел ибо было лень, но вот он я! :)

Качая главы с манга-чан(хз как на других) главы которые имеют вид типа "15.5" я получаю "155" в именах папок.

Спасибо за тяжкий труд!

**Comment by MonkAlex** [comment]
@ftugit с возвращением. Я немного сделал перерыв пока, но в целом рад всегда отзывам.

Твои идеи, как правильно именовать папку?
Тут основная идея в чём - надо делать сортировку по именам папок - 01, 10, 15. И цифра 15.5 никуда не вписывается, потому что большинство читалок сортирует папки по имени, т.е. 15.5 будет примерно там же, где 155.

Просто точку вернуть - можно попробовать.

**Comment by ftugit** [comment]
Я хз по поводу читалок ибо использую QuickPic, а для доступа к главам использую файловый менеджер.
В моем случае сортировка по имени в используемом мною MiXplorer по феншую т.е. 15.* будет после 15.

Ты лучше подумай, что будет если скачать мангу на 200+ глав, где 10-е главы имеют главы с точками. Я думаю либо папки получат имя типо "155[2]" либо тупо изображения 155й главы будут в 15.5 главе. Я встречал мангу где в первом томе к-во глав превышает 100, вопрос времени когда кто-то столкнется с данной ситуацией.

Я вижу 2 выхода:
1. Свой порядок глав т.е. если попадется глава 15.5, то она станет 16-й в имени папки, а 16-я станет 17-й и т.д.
2. Вернуть точки либо заменить их на минус(-). Надо смотреть из особенностей используемых тобой читалок.

**Comment by MonkAlex** [comment]
Такс, во первых - по пересечению названий.
Главы с точками, насколько я в курсе, это авторские бонусы для тех, кто купил танкобон. Типичный формат - по бонусной главе на том. Учитывая, что тома я кладу в разные папки, пересечений не должно быть, ибо 15.5 глава будет предположим во втором томе, а 155 - в каком нибудь двадцатом.

Во вторых, с сортировкой везде по разному к сожалению. На linux у меня сейчас порядок 15-15.5-16 строится правильно, а вот читалки на планшете к сожалению умудрились его прочитать как 15.5-15-16. Как было на windows - не помню. Я ещё поищу хорошие варианты.

**Comment by MonkAlex** [comment]
@ftugit А ещё, по поводу своего порядка глав.
Проблема с бонусными главами в том, что они часто появляются задним числом. Т.е. у тебя уже есть и 15 глава и 16, а через год появляется 15.5, собсна поэтому же она так отвратительно называется. Поэтому, нумеровать со сдвигом заранее - не получится. А делать разные нумерации в зависимости от того, есть бонусные главы или нет - сложно и выглядит странно. Таки пронумеровали мы 15 и 16, завтра выйдет 15.5 - что теперь делать то? Все существующее пытаться переименовать на +1?

В целом - скорее не будет какой то внутренней нумерации, она только усложняет всё, не давая реальной пользы.

**Comment by ftugit** [comment]
Я не сталкивался с ситуациями когда бонусные главы выходили задним числом. В чем проблема написать номер глав "как есть"?

**Comment by MonkAlex** [comment]
@ftugit а бог его знает. По идее да, можно и просто с точкой писать, хуже не станет.

**Comment by ftugit** [comment]
Если боишься проблем с читалками сделай данную фичу опционной.
Я уж точно тебе спасибо скажу ибо мне не придется читать начальные главы в конце манги.

**Comment by MonkAlex** [comment]
@ftugit читалкам хоть как плохо. Перепроверю все сайты и варианты на варианты с бонусными главами и добавлю точку наверно на неделе.

**Comment by MonkAlex** [comment]
Пока копался с точками, нашел ещё проблем в эту же тему.

http://mangachan.me/manga/5335-the-breaker-new-waves.html - 170.1 глава по ссылке распознается как 170 и скачивается видимо только одна из них, что печально.

А вот тут - http://mangachan.me/manga/9196-anima.html, бонусные главы вполне корректно указывают свой номер в ссылке и всё отлично.

Парсить названия глав для определения номера не хочется, так что надо подумать над нумерацией ещё.

**Comment by ftugit** [comment]
У берсерка для 170.1 главы один с 170 конечный url.
А что если составлять общее к-во ссылок и задать свою нумерацию? Хотя это противоречит проблеме младших глав которые добавили позже.

Чем тебе парсинг страницы не угодил?
На странице с читалкой есть div "a-series-volch volch" в единственном виде, там только Том n Глава n

**Comment by MonkAlex** [comment]
@ftugit прямо сейчас для получения глав и томов парсится только главная страница и это дешево с точки зрения времени и числа запросов. Парсить каждую страницу до явной загрузки картинок с неё - не хотелось, но может так и придётся делать.

Я ожидал простого и быстрого решения, но пока не получается.

**Comment by ftugit** [comment]
Можно парсить и главную страницу, просто придется больше информации срезать

**Comment by MonkAlex** [comment]
Хм, по моему стало ещё хуже. На читалку ещё закину.
![default](https://user-images.githubusercontent.com/6784764/29994286-2293c09c-8fdd-11e7-87d3-1c19391f5c5c.png)

**Comment by MonkAlex** [comment]
QuickPic ставит в правильном порядке, но он похоже даже не умеет между главами автоматически переключаться, неудобно же?

*чешет репу* думать надо дальше.

**Comment by MonkAlex** [comment]
@ftugit короче, мне нужна конкретная манга, где ты главу с точкой получаешь РАНЬШЕ, чем она задумана автором.

Потому как я думал проверить на http://mangachan.me/manga/5335-the-breaker-new-waves.html, но там всё правильно - единственная бонусная глава в конце тома, а остальное шлак, не имеющее к сюжету отношения.

**Comment by ftugit** [comment]
Я конечно извиняюсь, но я сразу говорил, что использую файловый менеджер для навигации между главами.
Моя претензия была в том, что главы с точкой становились сотыми. Из-за чего я доходил до данных глав в лучшем случае под конец арки, а в худшем под конец манги.
Я не могу привести желаемый тебе пример где в одном томе 100+ глав. По факту такие есть, но известные мне не имеют бонусных глав вообще.

Я прошу добавить возможность качать главы и назвать их "как есть"(т.е. главы будут иметь вид как предлагает читалка без лишних нулей). Если имеется проблема с манга-читалками(коими я не пользуюсь из-за убогости, известных мне, с масштабированием и дизайном), то добавить данную возможность "опционально".
**Если мои причины не являются должными(иначе говоря: мало актуальными в будущем), то просто закроем тему.**

**Comment by MonkAlex** [comment]
@ftugit я просто так и не нашел манги, где была бы реальная проблема.

Добавлять настройку не хочется, много настроек - сложнее всё это поддерживать.

Называть главы как есть - в плане прямо как они отображаются на сайте? Сайты их сортируют иногда совсем иначе и читалка твоя порядок потеряет совсем. Если речь только о нумерации - то тут хватает проблем, иногда номер разный в адресной строке и текстом забитый, текст при этом очевидно парсить в разы сложнее.

Давай так. Вот глава - http://mangachan.me/online/155514-berserk_v29_ch3.html
Как тебе хотелось бы чтобы называлась папка с этой главой?
Тут просто куча вариантов - "Berserk   v29 - 3   Тихий ужин" прямо с сайта, "Chapter 0003" как в текущей реализации, или просто "Chapter 3". Может у тебя другое видение, давай, опиши его, чтобы я понял, чего тебе хочется.

Хочется просто сделать один раз и нормально, а не переделывать каждый раз, как окажется неудобно.

**Comment by ftugit** [comment]
Как предлагает читалка. Разница и проблема только в том, что некоторые сайты имеют вместо списка выпадающий список следовательно лучше сделать данную опцию за отдельными сервисами(как и настройка куда качать мангу для отдельного сайта)

**Comment by MonkAlex** [comment]
@ftugit полностью оригинальные названия - неплохая идея. Тут уже явно настраиваемая, поэтому надо будет обдумать настройки.
Но да, это займет побольше времени. Подумаю над этим ближайшие недели.

**Comment by MonkAlex** [comment]
Итак, варианты. Первый врядли буду делать, слишком некрасиво смотрится.

Для параноиков, сложная схема с внутренней и внешней нумерацией
0030-3-{название главы}
0035-3-{название бонусной главы}
где 30 и 35 просто цифры без какого либо смысла, а 3 в обоих случаях внешний номер главы.

Для остальных нормальная схема
0003 {название главы}
0003.5 {название бонусной главы}

Плюс, поддержка старого именования, но теперь с точками
Chapter 0003
Chapter 0003.5

**Comment by MonkAlex** [comment]
Варианты 2-3 сделаны, надо ещё конвертер навалять и вынести в настройки визуально.

Не будет поддержки смены способа именования на лету. Т.е. старые папки переименовываться не будут.

**Comment by MonkAlex** [comment]
@ftugit ещё раз уточню, а то немного не уверен, то что надо делаю или нет.
Глава называется к примеру "Berserk   v35 - 7   Заложники моря ужаса"
Прямо сейчас это "Volume 035\Chapter 0007"
Я добавляю вариант "035 Volume\0007 Berserk   v35 - 7   Заложники моря ужаса"
Подумываю ещё над вариантом "035 Volume\0007 Chapter"

В каком виде тебе хотелось?

**Comment by ftugit** [comment]
Я не понимаю "035 Volume\0007 Berserk v35 - 7 Заложники моря ужаса". Зачем дублировать том и название?

Я хочу нумерацию с поддержкой точек. Получается глава "15 [название главы"  и 15.5 не станут 015 и 155 соответственно. Я просил чистые названия в том виде как их отдает сайт.

**Comment by MonkAlex** [comment]
@ftugit точки то я добавил, но мне ещё нужна нормальная сортировка.

Вариант с пользовательским вводом - сложный, пока я хотел сделать парочку предопредленных конфигов, расширение разве что в каком то далеком будущем.

Тома на самом деле добавлены в первую очередь для упаковки. Я понимаю, что ты не пользуешься, но в целом упаковка сильно спасает на устройствах с андроидом - быстрее копируется, быстрее читается и удаляется. Если нет томов, то упаковка остается либо по главам (а их может быть прямо очень много, опять снижение скорости), либо целиком, а тут обычно возникают проблемы уже с размером архива всей манги.

Короче, я не смогу прямо щас отказаться от томов, не сломав ничего.

ПС: поддержка парсеров уже есть, просто кто их писать то будет? Я сам обычно и пишу. Да, только на C# поддержка, не хочу изобретать какие то велосипеды типа сложных конфигов в которых надо описывать Regex для парсинга.

ПС2: таки делаю 3 формата, если конечно третий хоть кому то нужен, ибо мне только второй:
1. Старый, **Volume 001/Chapter 0003.5**
2. Новый по умолчанию **001 Volume/0003.5 Chapter**
3. Оригинальные названия глав **001 Volume/0003.5 Тут название конкретной главы**

**Comment by MonkAlex** [comment]
Такс, я в выходные планирую наконец то релизнуть это дело. Обкатаю на своих данных и надеюсь не найду проблем.
