### ISSUE TITLE
Обрезка названия

### ISSUE THREAD

**Issue by ftugit** [MonkAlex/MangaReader#98]
Скачал значит я мангу "Isekai de "Kuro no Iyashi Te" tte Yobarete Imasu", а на выходе получил папку "Isekai de" и имя в качалке "Isekai de\\\".

**Comment by MonkAlex** [comment]
Ссылку на мангу дай, чтобы я проверить мог =)

**Comment by ftugit** [comment]
http://mangachan.me/manga/48069-isekai-de-kuro-no-iyashi-te-tte-yobarete-imasu.html

**Comment by MonkAlex** [comment]
Вроде пофиксил, но оно в целом не критично, так что только это релизить не вижу смысла.
