### ISSUE TITLE
Пауза при закачке

### ISSUE THREAD

**Issue by ftugit** [MonkAlex/MangaReader#99]
После нажатия паузы загрузка продолжает идти еще около минуты, это норма?
![0000](https://user-images.githubusercontent.com/17074693/29694681-bf8b7c34-8946-11e7-8e97-95f8f04fe3bb.jpg)

UPD: во второй раз я уже минут 5 жду, она мне мангу собирается докачать???
UPD2: лол, точно. не угомонилась пока не скачала...

**Comment by MonkAlex** [comment]
Оно продолжает качать то, что уже начало (файлы), но не начинает качать следующие.
Второй вариант, который я обдумывал, когда делал -  будет скорее дропать файлы, которые успел начать качать к моменту паузы. И вроде как обидно дропать.

Проблема реальной паузы в том, что сервер не обязан поддерживать паузу - может взять и отопнуть тебя, если ты долго не докачивал файл.

**Comment by MonkAlex** [comment]
Потенциально, можно снизить число файлов, которые он заранее готов качать, я посмотрю.

**Comment by ftugit** [comment]
Я конечно не специалист, но почему не сделать просто остановку на последнем файле?
Допустим надо скачать 100 файлов, 10 скачалось, 11 качается. Когда 11-й скачается происходит пауза и так со всеми потоками.

**Comment by MonkAlex** [comment]
@ftugit скачивание параллельное, сразу много файлов тянется. Как минимум ридманга с минтмангой от этого прилично выигрывают.

**Comment by ftugit** [comment]
тогда у меня самый логичный вопрос:
а что будет с файлами если я прерву загрузку выключением ПК?

**Comment by MonkAlex** [comment]
Файлы пишутся только после полного скачивания, так что именно с файлами всё будет просто - они не запишутся.
Поэтому и говорю, что как вариант - можно прекращать скачивать то, что сейчас качается и это тоже будет паузой.

А можно уменьшить число одновременно качаемых файлов, сейчас не уверен сколько их, есть вероятность что может поставить в очередь прямо всё и тогда пауза будет только начиная со следующей манги.

**Comment by ftugit** [comment]
Получается файла докачаются после если ПК выключится?
Так почему так и паузу не реализовать? Заодно и новую мангу можно будет добавлять.

**Comment by MonkAlex** [comment]
Не обещаю, что получится легко и быстро, но сделать попробую.

**Comment by MonkAlex** [comment]
В целом, удалось оптимизировать паузу. Работает как и раньше, но быстрее останавливается, на хороших интернетах - буквально за 2-3 секунды. В ближайший релиз попадёт, проверишь.
